// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0aGVWxWtl8w1mgvDezRh2kqUFBCF1USY',
    appId: '1:460108735206:web:7a995fb4dc3cf92d3d1127',
    messagingSenderId: '460108735206',
    projectId: 'flutter-riverpod-sample',
    authDomain: 'flutter-riverpod-sample.firebaseapp.com',
    storageBucket: 'flutter-riverpod-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzg-23q-_6B2ZThqlNHHMnYKcPELevm8E',
    appId: '1:460108735206:android:863195d337a761193d1127',
    messagingSenderId: '460108735206',
    projectId: 'flutter-riverpod-sample',
    storageBucket: 'flutter-riverpod-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFJb1El6eVjOORp48u7uY_xssru19VPOs',
    appId: '1:460108735206:ios:5edc34c291b2155c3d1127',
    messagingSenderId: '460108735206',
    projectId: 'flutter-riverpod-sample',
    storageBucket: 'flutter-riverpod-sample.appspot.com',
    iosClientId: '460108735206-p24suqad5fg2b2elr4iefo0e1kl7cmor.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHooksExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFJb1El6eVjOORp48u7uY_xssru19VPOs',
    appId: '1:460108735206:ios:5edc34c291b2155c3d1127',
    messagingSenderId: '460108735206',
    projectId: 'flutter-riverpod-sample',
    storageBucket: 'flutter-riverpod-sample.appspot.com',
    iosClientId: '460108735206-p24suqad5fg2b2elr4iefo0e1kl7cmor.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHooksExample',
  );
}
